#index:
#    path: /
#    controller: App\Controller\DefaultController::index


homepage_translation:
    path: /{_locale}
    controller: App\Controller\DefaultController::homepage
    defaults:
      _locale: en
    requirements:
      _locale: 'en|fr'
   
add_product:
    path: /{_locale}/add/product
    controller: App\Controller\ProductController::addProduct
    defaults:
      _locale: en
    requirements:
      _locale: 'en|fr'
      
list_product:
    path: /{_locale}/list/product
    controller: App\Controller\ProductController::listProduct
    defaults:
      _locale: en
    requirements:
      _locale: 'en|fr'      
    
add_user:
    path: /{_locale}/add/user
    controller: App\Controller\UserController::addUser
    defaults:
      _locale: en
    requirements:
      _locale: 'en|fr'
      
username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']      
    
user_activate:
    path: /{_locale}/user/activate/{token}
    controller: App\Controller\UserController::activateUser
    defaults:
      _locale: en
    requirements:
         token: '[a-z0-9-]+'
         _locale: 'en|fr'
         
login:
    path: /login
    controller:  App\Controller\UserController::login 
logout:
    path: /logout  
         
product_details:
    path: /{_locale}/product/details
    controller: App\Controller\ProductController::detailProduct
    
    
    
    
    